spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    defer-datasource-initialization: true
security:
  oauth2:
    client:
      client-id: framework
      client-secret: framework

jwt:
  secret: JWT-SECRET
  duration: 86400
